### ISSUE TITLE
request: make qt optional

### ISSUE THREAD

**Issue by CamilleScholtz** [MihaiBojescu/Linux-notifier#2]
Hi, I don't know if something like IFDEF or optional dependencies is possible with python, but it would be really nice if you made the GUI stuff optional, because qt5 and it's deps is quite big :).

**Comment by MihaiBojescu** [comment]
Hi. I would make it optional but I don't know how to make authentication work without a GUI. I can make it auto-accept auth requests, but that would be a security hole. I can make a separate logic inside the script so it would act like a shell and accept incoming auth requests, but that wouldn't be automatic. It would be like you have to open the script first, open the android client, click on the client on android, prompt for y/n, then close the script. This must be done everytime a new android client wants to authenticate and it would be tedious for the user to do it.

On the other hand, if you want GTK support support, I can do it no questions asked.

Personally I would love to make it GUI-less, but as you can see, it would be tedious on the user (edit: and the main goal of this script was to make it painless).

**Comment by CamilleScholtz** [comment]
>I can make it auto-accept auth requests, but that would be a security hole.

Maybe some kind of flag and/or file with fingerprints of allowed devices? Anyways I must admit I don't know a whole lot about either security or sockets :).

Optionally you could use notifications to for authentication, I'm pretty sure you can set an action on click.

**Comment by MihaiBojescu** [comment]
I'll go with the idea with notification buttons. How didn't I think about this earlier?

**Comment by MihaiBojescu** [comment]
Update: I will implement this the following days, as I have a very tight schedule for now. It will come for sure, no worries :).

**Comment by MihaiBojescu** [comment]
Fixed :). It now uses notifications are requested. I'm sorry it took so long to implement.

**Comment by CamilleScholtz** [comment]
Works like a charm!
